name: Bug or errata
description: Report a problem in the draft or examples
title: "[Bug] <short summary>"
labels: ["bug"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's wrong?
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the docs?
  - type: textarea
    id: fix
    attributes:
      label: Proposed fix
      description: Optional suggested text
