name: Data submission
description: Submit pilot results for $·s/task benchmarking
title: "[Data] <provider>/<model> on <task>"
labels: ["data"]
body:
  - type: markdown
    attributes:
      value: "Attach a CSV or link with: median, p10, p90 for $·s/task, $/task, s/task; success@Q; metadata (provider, model ID, tier, region, dates, caching toggles)."
  - type: input
    id: task
    attributes:
      label: Task (benchmark + quality criterion Q)
      placeholder: "e.g., GSM8K (exact match), HumanEval (pass@1)"
  - type: input
    id: provider
    attributes:
      label: Provider & model ID
      placeholder: "e.g., Vendor A — Model X"
  - type: input
    id: tier
    attributes:
      label: Plan tier
      placeholder: "e.g., Plus, Pro, Team, Enterprise, API rate"
  - type: input
    id: region
    attributes:
      label: Region
      placeholder: "e.g., us-east, eu-west, ap-southeast"
  - type: textarea
    id: stats
    attributes:
      label: Summary statistics
      placeholder: "median/p10/p90 for $·s/task, $/task, s/task; success@Q with CI"
  - type: textarea
    id: method
    attributes:
      label: Method notes
      placeholder: "Sampling params, caching toggles, seeds, any deviations"
