name: Proposal feedback
description: Comment on definitions, metrics, protocol, or compliance levels
title: "[Feedback] <short summary>"
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reviewing LBBS. Please be specific and actionable."
  - type: textarea
    id: section
    attributes:
      label: Section(s)
      description: Which sections does your feedback address?
      placeholder: "e.g., 3. Standardized Metrics; 4.2 Run Conditions"
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
      description: What change should we make? Provide proposed text if possible.
  - type: textarea
    id: rationale
    attributes:
      label: Rationale & evidence
      description: Please provide data, citations, or examples.
